name: TeleportTolls
main: com.armeniumstudios.teleporttolls.TeleportTolls
version: "0.1.0"
api-version: 1.16
author: Armenium
description: Configure teleport tolls
website: www.armeniumstudios.com
depends: [Vault]
commands:
  language:
    description: "Allows you to change your language"
    usage: /language
    aliases: [locale, lang]